/** Run against the disposable notes test API, same setup as notes-browser.cjs. */
const assert=require('node:assert/strict');const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH || '/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const base=process.env.NOTES_URL || 'http://127.0.0.1:3001';let created=[];
for(const n of [1,3,4,6]){const sections=Array.from({length:n},(_,i)=>({id:'s'+i,title:'目录 '+i,order:i}));const units=Array.from({length:8},(_,i)=>({id:'u'+i,title:i===0?'特别长的知识单元名称'.repeat(18):'知识单元'+i,sectionId:'s'+(i%n),content:'# 标题\n\n正文',tags:[]}));const r=await page.request.post(base+'/api/notes/topics',{data:{title:'布局验收'+n,sections,units,preferredColumns:n}});assert.equal(r.status(),201);const t=await r.json();created.push(t.id);await page.goto(base+'/notes/'+t.id);await page.locator('.unit-card').first().waitFor();const cols=await page.locator('.unit-grid').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length);assert.ok(n===1?cols===1:cols>1);await page.getByRole('button',{name:'学习路线',exact:true}).click();assert.equal(await page.locator('.graph-heading span').count(),n);const boxes=await page.locator('.graph-node').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().height));assert.ok(boxes.every(h=>h<90));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}
const id=created[1];await page.goto(base+'/notes/'+id+'?section=s1&q=知识&view=directory');await page.locator('[data-unit-id]').first().waitFor();const opener=await page.locator('[data-unit-id]').first().getAttribute('data-unit-id');await page.locator('[data-unit-id]').first().focus();await page.keyboard.press('Enter');await page.getByRole('button',{name:'编辑',exact:true}).waitFor();await page.keyboard.press('Escape');await page.locator('[role=dialog]').waitFor({state:'hidden'});assert.equal(new URL(page.url()).searchParams.get('q'),'知识');assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('data-unit-id')),opener);
// Persisted renaming/order/columns and delete empty metadata via UI.
await page.getByRole('button',{name:'主题设置',exact:true}).click();await page.getByRole('textbox',{name:'主题名称',exact:true}).fill('重命名主题');await page.getByRole('spinbutton',{name:'排序位置（数字越小越靠前）',exact:true}).fill('0');await page.getByRole('spinbutton',{name:'工作区偏好列数',exact:true}).fill('1');await page.getByRole('button',{name:'保存设置',exact:true}).click();await page.locator('[role=dialog]').waitFor({state:'hidden'});await page.reload();await page.getByRole('heading',{name:'重命名主题',exact:true}).waitFor();assert.equal(await page.locator('.unit-grid').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length),1);
await page.getByRole('button',{name:'设置目录 目录 1',exact:true}).click();await page.getByRole('textbox',{name:'目录名称',exact:true}).fill('重命名目录');await page.getByRole('spinbutton').fill('0');await page.getByRole('button',{name:'保存设置',exact:true}).click();await page.locator('[role=dialog]').waitFor({state:'hidden'});await page.reload();await page.getByRole('button',{name:'重命名目录',exact:true}).waitFor();
const empty=await (await page.request.post(base+'/api/notes/topics',{data:{title:'待删除空主题'}})).json();await page.goto(base+'/notes/'+empty.id);await page.getByRole('button',{name:'主题设置',exact:true}).click();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'删除主题',exact:true}).click();await page.waitForURL(base+'/notes');assert.equal((await page.request.get(base+'/api/notes/topics/'+empty.id)).status(),404);
console.log('PASS dynamic 1/3/4/6 sections, long title geometry, preferred columns, query/focus restoration, persisted metadata/order, empty-topic deletion');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
